# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Venus-Protocol

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:
jobs:
  test:
    name: Test
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Clear
        run: docker system prune -f -a --volumes

      - name: Build docker
        run: docker build -t venus:${GITHUB_SHA::7} .

      - name: Run tests
        run: docker run --name ${GITHUB_SHA::7} venus:${GITHUB_SHA::7} yarn test

      - name: Clear
        run: docker rm ${GITHUB_SHA::7}

      - name: Run hardhat compile and tests coverage
        run: |
          yarn compile && yarn coverage

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/**/cobertura-coverage.xml
          badge: true
          fail_below_min: false
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: "50 80"

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: "yarn"

      - name: Install dependencies
        # Hack to get around failing "ethereumjs-abi The remote archive doesn't match the expected checksum" error
        run: YARN_CHECKSUM_BEHAVIOR=update yarn

      - name: Lint solidity and ts files
        run: yarn lint

  docgen:
    name: Docgen
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: "yarn"

      - name: Install dependencies
        # Hack to get around failing "ethereumjs-abi The remote archive doesn't match the expected checksum" error
        run: YARN_CHECKSUM_BEHAVIOR=update yarn

      - name: Lint soliditidy and ts files
        run: yarn docgen
